# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ImgData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ImgData.proto',
  package='protocol',
  syntax='proto3',
  serialized_options=_b('\n\021cn.csg.gjdl.robotB\013ImgDataBean'),
  serialized_pb=_b('\n\rImgData.proto\x12\x08protocol\"[\n\x07ImgData\x12\x10\n\x08msg_type\x18\x01 \x01(\x05\x12\x0e\n\x06length\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\x0f\n\x07imgdata\x18\x05 \x01(\x0c\x42 \n\x11\x63n.csg.gjdl.robotB\x0bImgDataBeanb\x06proto3')
)




_IMGDATA = _descriptor.Descriptor(
  name='ImgData',
  full_name='protocol.ImgData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_type', full_name='protocol.ImgData.msg_type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='protocol.ImgData.length', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='protocol.ImgData.width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='protocol.ImgData.height', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imgdata', full_name='protocol.ImgData.imgdata', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=118,
)

DESCRIPTOR.message_types_by_name['ImgData'] = _IMGDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImgData = _reflection.GeneratedProtocolMessageType('ImgData', (_message.Message,), dict(
  DESCRIPTOR = _IMGDATA,
  __module__ = 'ImgData_pb2'
  # @@protoc_insertion_point(class_scope:protocol.ImgData)
  ))
_sym_db.RegisterMessage(ImgData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
